import {
  Users,
  Repeat,
  Crown,
  FileSignature,
  Handshake,
  BadgeCheck,
  Globe,
  Smartphone,
  Code2,
  PenTool,
  Layers,
  Cloud,
  Briefcase,
  ClipboardCheck,
  GraduationCap,
} from "lucide-react";
// group: staff | dev | hr   (slug is used in /service-detail?s=slug)
export const SERVICES = [
  {
    slug: "volume-hiring",
    g: "staff",
    I: Users,
    t: "Volume Hiring",
    short: "Many roles, filled fast.",
    d: "Hire large teams on a tight timeline. We run structured sourcing, screening and onboarding so you can scale without losing quality.",
    pts: [
      "Bulk sourcing and screening",
      "Scheduled interview drives",
      "Onboarding coordination",
      "Weekly progress reporting",
    ],
  },
  {
    slug: "rpo",
    g: "staff",
    I: Repeat,
    t: "RPO",
    short: "Your hiring team, on demand.",
    d: "Recruitment Process Outsourcing puts our recruiters inside your hiring process, from workforce planning to offer, for a predictable cost.",
    pts: [
      "Dedicated recruiter team",
      "Employer-brand aligned outreach",
      "Pipeline and KPI dashboards",
      "Flexible scale up or down",
    ],
  },
  {
    slug: "executive-hiring",
    g: "staff",
    I: Crown,
    t: "Executive Hiring",
    short: "Leaders found with discretion.",
    d: "Confidential, research-led search for senior and critical leadership roles, backed by direct outreach and careful assessment.",
    pts: [
      "Confidential search",
      "Direct approach to talent",
      "Leadership assessment",
      "Offer and notice support",
    ],
  },
  {
    slug: "contract",
    g: "staff",
    I: FileSignature,
    t: "Contract",
    short: "Skilled people for defined work.",
    d: "Bring in vetted professionals for projects, seasonal peaks or short-term gaps. We handle sourcing, contracts and payroll.",
    pts: [
      "Ready-to-deploy talent",
      "Contract and payroll handling",
      "Fast replacements",
      "Extension on demand",
    ],
  },
  {
    slug: "contract-to-hire",
    g: "staff",
    I: Handshake,
    t: "Contract to Hire",
    short: "Try the fit, then hire.",
    d: "Start with a contract, see the work first-hand, and convert to a permanent role when both sides are confident.",
    pts: [
      "Evaluation period built in",
      "Smooth conversion process",
      "Reduced hiring risk",
      "Clear terms from day one",
    ],
  },
  {
    slug: "full-time",
    g: "staff",
    I: BadgeCheck,
    t: "Full Time",
    short: "Permanent hires that stay.",
    d: "End-to-end permanent placement: understanding the role, finding the match, and guiding the offer through to joining.",
    pts: [
      "Role and culture briefing",
      "Shortlisted, interview-ready profiles",
      "Offer negotiation support",
      "Post-joining follow-up",
    ],
  },
  {
    slug: "web-development",
    g: "dev",
    I: Globe,
    t: "Web Development",
    short: "Scalable digital experiences.",
    d: "Build fast, responsive and scalable websites and web applications tailored to your business.",
    pts: [
      "Responsive websites and web apps",
      "Performance and SEO built in",
      "CMS and e-commerce",
      "Maintenance and support",
    ],
  },
  {
    slug: "mobile-development",
    g: "dev",
    I: Smartphone,
    t: "Mobile Development",
    short: "Powerful apps for every platform.",
    d: "Create intuitive, high-performance mobile applications for Android and iOS.",
    pts: [
      "Android and iOS apps",
      "Cross-platform builds",
      "Store launch support",
      "Analytics and updates",
    ],
  },
  {
    slug: "custom-software",
    g: "dev",
    I: Code2,
    t: "Custom Software",
    short: "Solutions built for your business.",
    d: "Develop secure, scalable software solutions designed around your unique business requirements.",
    pts: [
      "Requirement discovery",
      "Secure, scalable architecture",
      "Integrations with your tools",
      "Long-term support",
    ],
  },
  {
    slug: "ui-ux",
    g: "dev",
    I: PenTool,
    t: "UI/UX Development",
    short: "Experiences users love.",
    d: "Create modern, engaging and user-friendly digital experiences that combine great design with usability.",
    pts: [
      "Research and user flows",
      "Wireframes and prototypes",
      "Design systems",
      "Design-to-code delivery",
    ],
  },
  {
    slug: "full-stack",
    g: "dev",
    I: Layers,
    t: "Full-Stack Development",
    short: "Complete end-to-end solutions.",
    d: "Build complete applications covering frontend, backend, APIs, databases and integrations.",
    pts: [
      "Frontend and backend",
      "APIs and databases",
      "Third-party integrations",
      "Testing and deployment",
    ],
  },
  {
    slug: "cloud-devops",
    g: "dev",
    I: Cloud,
    t: "Cloud & DevOps",
    short: "Deploy. Scale. Perform.",
    d: "Deploy, manage and scale applications with reliable cloud infrastructure, automation, monitoring and security.",
    pts: [
      "Cloud setup and migration",
      "CI/CD automation",
      "Monitoring and alerts",
      "Security and cost control",
    ],
  },
  {
    slug: "hr-consulting",
    g: "hr",
    I: Briefcase,
    t: "HR Consulting",
    short: "People strategy that works.",
    d: "Practical HR advisory covering policies, structures and people processes, shaped around the size and stage of your business.",
    pts: [
      "HR policy and handbook support",
      "Role and structure design",
      "Compliance guidance",
      "Ongoing HR advisory",
    ],
  },
  {
    slug: "talent-assessment",
    g: "hr",
    I: ClipboardCheck,
    t: "Talent Assessment",
    short: "Know the fit before you hire.",
    d: "Structured assessments and interview frameworks that help you judge skills, role fit and potential with confidence.",
    pts: [
      "Skills and role-fit assessments",
      "Interview frameworks",
      "Candidate evaluation reports",
      "Team capability reviews",
    ],
  },
  {
    slug: "training-onboarding",
    g: "hr",
    I: GraduationCap,
    t: "Training & Onboarding",
    short: "Ready from day one.",
    d: "Job-oriented training and a clear onboarding journey that help new hires settle in quickly and contribute sooner.",
    pts: [
      "Role-based training programs",
      "Structured onboarding plans",
      "Induction and documentation",
      "Progress check-ins",
    ],
  },
];
export const GROUPS = {
  staff: "Staffing Services",
  dev: "Development Services",
  hr: "HR Consulting",
};
export const bySlug = (s) => SERVICES.find((x) => x.slug === s) || SERVICES[0];
export const TICKER = [
  "Volume Hiring",
  "RPO",
  "Executive Hiring",
  "Web Development",
  "Mobile Apps",
  "Cloud & DevOps",
  "HR Consulting",
  "Talent Assessment",
  "Contract to Hire",
  "Full-Stack Development",
  "Training & Onboarding",
];
